// https://w3c.github.io/ServiceWorker/#clients-interface
[Exposed=ServiceWorker]
interface Clients {
    // FIXME: get()/matchAll()/openWindow() are not implemented - only claim() is, since that's the only
    //        member Flutter's flutter_service_worker.js calls.
    [NewObject] Promise<undefined> claim();
};
